/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quarto.view;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import quarto.bean.QuartoBean;
import quarto.dao.QuartoDao;

/**
 *
 * @author carlos
 */
public class FormPesquisaQuarto extends javax.swing.JDialog {
    private QuartoDao quartoDao;
    /**
     * Creates new form FormPesquisaQuarto
     */
    public FormPesquisaQuarto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        instanciaClasses();
        carregaTabelaQuarto();
    }
    
    private void instanciaClasses() {
        //Padrão Singleton
        if (quartoDao == null) {
            quartoDao = new QuartoDao();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCBPesquisa = new javax.swing.JComboBox<>();
        jTFPesquisa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExluir = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBPesquisa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de Quartos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));

        jCBPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "N° do Quarto" }));
        jCBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPesquisaActionPerformed(evt);
            }
        });

        jTFPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExluir.setText("Excluir");
        jBExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExluirActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBExluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExluir)
                    .addComponent(jBFechar))
                .addContainerGap())
        );

        jTBPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTBPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBPesquisaMouseClicked(evt);
            }
        });
        jTBPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTBPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBPesquisaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTBPesquisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        dispose();
        cadastrarQuarto();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        dispose();
        alterarQuarto();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExluirActionPerformed
        excluir();
        jTFPesquisa.grabFocus();
    }//GEN-LAST:event_jBExluirActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        fecharTela();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fecharTela();
    }//GEN-LAST:event_formWindowClosing

    private void jTBPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBPesquisaMouseClicked
        int count = evt.getClickCount();
        if (count == 2) {
            abreFormDependente();
        }
    }//GEN-LAST:event_jTBPesquisaMouseClicked

    private void jTBPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
            abreFormDependente();
        }
    }//GEN-LAST:event_jTBPesquisaKeyPressed

    private void jTBPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBPesquisaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP && jTBPesquisa.getSelectedRow() == 0) {
            jTFPesquisa.grabFocus();
        }
    }//GEN-LAST:event_jTBPesquisaKeyReleased

    private void jCBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPesquisaActionPerformed
        jTFPesquisa.grabFocus();
    }//GEN-LAST:event_jCBPesquisaActionPerformed

    private void jTFPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPesquisaKeyReleased
        jTFPesquisa.setText(jTFPesquisa.getText().toUpperCase());
        String dado = jTFPesquisa.getText();
        if (!dado.equals("")) {
            if (jCBPesquisa.getSelectedIndex() == 0) {
                populaTabelaQuarto((ArrayList<QuartoBean>) quartoDao.pesquisarPorCodigo(new Integer(dado)));
            } else {
                populaTabelaQuarto((ArrayList<QuartoBean>) quartoDao.pesquisarPorNumDoQuarto(dado));
            }
        } else {
            populaTabelaQuarto((ArrayList<QuartoBean>) quartoDao.listar());
        }
        selecionaPrimeiraLinhaDaTabela();
    }//GEN-LAST:event_jTFPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPesquisaQuarto dialog = new FormPesquisaQuarto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cadastrarQuarto() {
        FormCadQuarto formCadQurto = new FormCadQuarto(null, true);
        formCadQurto.setVisible(true);
    }

    private void alterarQuarto() {
        QuartoBean quartoBean = pegaQuartoSelecionado();
        if (quartoBean != null) {
            FormCadQuarto formCadQurto = new FormCadQuarto(quartoBean);
            formCadQurto.setVisible(true);
        }
    }

    private QuartoBean pegaQuartoSelecionado() {
        if (verificarLinhaSelecionada()) {
            return (QuartoBean) (jTBPesquisa.getValueAt(jTBPesquisa.getSelectedRow(), -1));
        }
        return null;
    }
    
    private void populaTabelaQuarto(ArrayList<QuartoBean> lista) {
        QuartoTableModel modeloQuarto = new QuartoTableModel(lista);
        jTBPesquisa.setModel(modeloQuarto);
        jTBPesquisa.getTableHeader().setFont(new Font("Ubuntu", 1, 12));
        definirTamanhoColunas();
        definirAlinhamentoColunas();
        selecionaPrimeiraLinhaDaTabela();
    }
    
    private void definirTamanhoColunas() {
        jTBPesquisa.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTBPesquisa.getColumnModel().getColumn(1).setPreferredWidth(130);
        jTBPesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTBPesquisa.getColumnModel().getColumn(3).setPreferredWidth(67);
    }
    
    private void definirAlinhamentoColunas() {
        DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
        rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer rendererDireita = new DefaultTableCellRenderer();
        rendererDireita.setHorizontalAlignment(SwingConstants.RIGHT);
        DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();
        rendererEsquerda.setHorizontalAlignment(SwingConstants.LEFT);

        jTBPesquisa.getColumnModel().getColumn(0).setCellRenderer(rendererCentro);
        jTBPesquisa.getColumnModel().getColumn(1).setCellRenderer(rendererEsquerda);
        jTBPesquisa.getColumnModel().getColumn(2).setCellRenderer(rendererEsquerda);
        jTBPesquisa.getColumnModel().getColumn(3).setCellRenderer(rendererEsquerda);
    }
    
    public void carregaTabelaQuarto() {
        populaTabelaQuarto((ArrayList<QuartoBean>) quartoDao.listar());
    }
    
    private void excluir() {
        if (verificarLinhaSelecionada()) {
            int[] linhas = jTBPesquisa.getSelectedRows();
            QuartoBean quartoBean;
            for (int i = 0; i < linhas.length; i++) {
                quartoBean = (QuartoBean) jTBPesquisa.getValueAt(linhas[i], -1);
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o quarto " + quartoBean.getNumeroDoQuarto()+ "?") == 0) {
                    if (excluirQuarto(quartoBean)) {
                        JOptionPane.showMessageDialog(null, "Quarto " + quartoBean.getNumeroDoQuarto()+ " excluído com sucesso!");
                    }
                }
            }
            carregaTabelaQuarto();
        }
    }

    private boolean excluirQuarto(QuartoBean quartoBean) {
        return quartoDao.excluir(quartoBean.getCodigo());
    }

    private boolean verificarLinhaSelecionada() {
        int linhaSelecionada = jTBPesquisa.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Quarto!");
            return false;
        }
        return true;
    }

    private void fecharTela() {
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente fechar o Formulário de Pesquisa de Quartos?") == 0) {
            dispose();
        }
    }
    
    private void selecionaPrimeiraLinhaDaTabela() {
        if (jTBPesquisa.getRowCount() > 0) {
            jTBPesquisa.getSelectionModel().setSelectionInterval(0, 0);
        }
    }
    
    private void setaFocoTabela() {
        if (jTBPesquisa.getRowCount() > 0) {
            jTBPesquisa.grabFocus();
        }
    }
    
    private void abreFormDependente() {
        alterarQuarto();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExluir;
    private javax.swing.JButton jBFechar;
    private javax.swing.JComboBox<String> jCBPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBPesquisa;
    private javax.swing.JTextField jTFPesquisa;
    // End of variables declaration//GEN-END:variables
}
